export default 
  [
    {
      letter: "А",
      word: "АВТОБУС", 
      pic: "pic_1",
      sound: "sound_1", 
    },
    {
      letter: "Б",
      word: "БІЛКА", 
      pic: "pic_2",
      sound: "sound_2", 
    },
    {
      letter: "В",
      word: "ВЕДМІДЬ", 
      pic: "pic_3", 
      sound: "sound_3", 
    },
    {
      letter: "Г",
      word: "ГРУША", 
      pic: "pic_4", 
      sound: "sound_4", 
    },
    {
      letter: "Ґ",
      word: "ҐУДЗИК", 
      pic: "pic_5",
      sound: "sound_5", 
    },
    {
      letter: "Д",
      word: "ДІМ", 
      pic: "pic_6",
      sound: "sound_6", 
    },
    {
      letter: "Е",
      word: "ЕКСКАВАТОР",
      pic: "pic_7",
      sound: "sound_7", 
    },
    {
      letter: "Є", 
      word: "ЄНОТ",
      pic: "pic_8",
      sound: "sound_8", 
    },
    {
      letter: "Ж", 
      word: "ЖИРАФ",
      pic: "pic_9",
      sound: "sound_9", 
    },
    {
      letter: "З", 
      word: "ЗАЄЦЬ",
      pic: "pic_10",
      sound: "sound_10", 
    },
    {
      letter: "И", 
      word: "СИР",
      pic: "pic_11",
      sound: "sound_11", 
    },
    {
      letter: "І",
      word: "ІГРАШКА",
      pic: "pic_12",
      sound: "sound_12", 
    },
    {
      letter: "Ї", 
      word: "ЇЖАК",
      pic: "pic_13",
      sound: "sound_13", 
    },
    {
      letter: "Й", 
      word: "ЙОГУРТ",
      pic: "pic_14",
      sound: "sound_14", 
    },
    {
      letter: "К", 
      word: "КІТ",
      pic: "pic_15",
      sound: "sound_15", 
    },
    {
      letter: "Л", 
      word: "ЛИСИЦЯ",
      pic: "pic_16",
      sound: "sound_16", 
    },
    {
      letter: "М",
      word: "МАВПА",
      pic: "pic_17",
      sound: "sound_17", 
    },
    {
      letter: "Н", 
      word: "НОСОРІГ",
      pic: "pic_18",
      sound: "sound_18", 
    },
    {
      letter: "О", 
      word: "ОЛІВЕЦЬ",
      pic: "pic_19",
      sound: "sound_19", 
    },
    {
      letter: "П",
      word: "ПАПУГА",
      pic: "pic_20",
      sound: "sound_20", 
    },
    {
      letter: "Р", 
      word: "РОБОТ",
      pic: "pic_21",
      sound: "sound_21", 
    },
    {
      letter: "С",
      word: "СЛОН",
      pic: "pic_22",
      sound: "sound_22", 
    },
    {
      letter: "Т", 
      word: "ТОРТ",
      pic: "pic_23",
      sound: "sound_23", 
    },
    {
      letter: "У", 
      word: "УДАВ",
      pic: "pic_24",
      sound: "sound_24", 
    },
    {
      letter: "Ф", 
      word: "ФАРБИ",
      pic: "pic_25",
      sound: "sound_25", 
    },
    {
      letter: "Х", 
      word: "ХОМ'ЯК",
      pic: "pic_26",
      sound: "sound_26", 
    },
    {
      letter: "Ц", 
      word: "ЦУКЕРКА",
      pic: "pic_27",
      sound: "sound_27", 
    },
    {
      letter: "Ч", 
      word: "ЧЕРЕПАХА",
      pic: "pic_28",
      sound: "sound_28", 
    },
    {
      letter: "Ш", 
      word: "ШПАК",
      pic: "pic_29",
      sound: "sound_29", 
    },
    {
      letter: "Щ", 
      word: "ЩІТКА",
      pic: "pic_30",
      sound: "sound_30", 
    },
    {
      letter: "Ь", 
      word: "КІНЬ",
      pic: "pic_31",
      sound: "sound_31", 
    },
    {
      letter: "Ю", 
      word: "ЮРТА",
      pic: "pic_32",
      sound: "sound_32", 
    },
    {
      letter: "Я", 
      word: "ЯБЛУКО",
      pic: "pic_33",
      sound: "sound_33", 
    },
  ]